### ISSUE TITLE
Add central Gulf of Mexico coast

### ISSUE THREAD

**Issue by dziban303** [rikgale/VRSCustomLayers#1]
Hey, creating an issue as directed. I'd like to get the custom layers to work around me in New Orleans. Since I can see Mississippi as well as Louisiana, and since I'd like to include the oil rigs out in the gulf, the larger of which have ICAO airport codes, I thought it'd be easiest if I use a bounding box.

The coordinates I was going to use were `-86,28.5,-93,31` in the `min x, min y, max x, max y` format required by the OpenAIP downloader.

**Comment by rikgale** [comment]
Gonna close this. Apart from gliding sites you should have it all now.
