### ISSUE TITLE
Undefined errors on Civil airport layers

### ISSUE THREAD

**Issue by speedst3r** [rikgale/VRSCustomLayers#18]
I have recently enabled custom layers on my VRS install, however when using the AU layers there is a undefined value script error at [line 149 of EndOfBody.html](https://github.com/rikgale/VRSCustomLayers/blob/3114d6476916659c424e881d4a8ed4c3f783a852/EndOfBody.html#L149)

```
for (j=0;j<feature.properties.runways.length;j=j+1){
```

A number of airports in the layer do not have any runways listed, so this line throws an error and no layers are rendered, nor does the menu appear in the bottom left.

I wrapped the block that enumerates runways in an undefined check and it seems to have got it working.

```
                        if (feature.properties.runways != undefined) {
                        // Runways Row
                        popupcontent = popupcontent + "<tr><td><b>Runways:</b></td><td>";
                        for (j=0;j<feature.properties.runways.length;j=j+1){
                                var runstring = "<span>"+feature.properties.runways[j].designator+"&nbsp;</span>";
                                popupcontent = popupcontent+runstring}
                        }
```

Not sure if this would have any side effects but raising it for visibility. Yes I could fork and raise a PR but it seemed like overkill for two lines :-)

**Comment by rikgale** [comment]
Many thanks for raising. I will look into this and add your code next time I get some hobby time. :)

**Comment by rikgale** [comment]
All added. Let me know if it fixes the issue you had and I'll close. TY.
