### ISSUE TITLE
India

### ISSUE THREAD

**Issue by DevInArmor** [rikgale/VRSCustomLayers#28]
Could we get an India layer.

**Comment by rikgale** [comment]
Hey. Yes, I will add to the list of areas to do

**Comment by rikgale** [comment]
Added for you. The were no Military, Glider or Navaid sites listed in the OpenAIP data source for India. You will still need to download the blank files for the script to work properly. If any details are incorrect they will need to be changed on OpenAIP.

If you use the SDR-E VRS docker container (https://github.com/sdr-enthusiasts/docker-virtualradarserver) then you will need to wait for the container to be updated to use these new file.
