### ISSUE TITLE
Indonesia

### ISSUE THREAD

**Issue by faninura** [rikgale/VRSCustomLayers#31]
Could we get an Indonesia layer? TIA.

**Comment by rikgale** [comment]
I'll add it too the list of things to do. :)

**Comment by rikgale** [comment]
Added for you. The were no Military or Glider sites listed in the OpenAIP data source for Indonesia. You will still need to download the blank files for the script to work properly. If any details are incorrect they will need to be changed on OpenAIP.

If you use the SDR-E VRS docker container (https://github.com/sdr-enthusiasts/docker-virtualradarserver) then you will need to wait for the container to be updated to use these new file.
