### ISSUE TITLE
Data for France

### ISSUE THREAD

**Issue by minou-miaou** [rikgale/VRSCustomLayers#32]
Hi.
Can you make enhanced layers data for France please ?
Thank you.

**Comment by rikgale** [comment]
I will do this next time I am making a batch.  :)

**Comment by minou-miaou** [comment]
Many thanks !

**Comment by rikgale** [comment]
Hi. This has been done. If you are using the sdr-enthusiasts/docker-virtualradarserver version of VRS, this should come in overnight. You may need to pull the latest version of the container. 
Any data that is wrong or missing - you'll need to add yourself to OpenAIP

**Comment by minou-miaou** [comment]
Thank you.
