### ISSUE TITLE
code for spain

### ISSUE THREAD

**Issue by olodeiro74** [rikgale/VRSCustomLayers#33]
Please code for Spain 
thanks

**Comment by rikgale** [comment]
I will do this next time I am making a batch.  :)

**Comment by rikgale** [comment]
Hi. This has been done. If you are using the sdr-enthusiasts/docker-virtualradarserver version of VRS, this should come in overnight. You may need to pull the latest version of the container. 
Any data that is wrong or missing - you'll need to add yourself to OpenAIP
